use_frameworks!

platform :ios, '8.0'

target 'HSYMacroKit_Example' do
  pod 'HSYMacroKit', :path => '../'

  target 'HSYMacroKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
